<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Konfigurasi Jekyll (config.yml)</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>

  <!-- Navbar -->
  <nav>
    <a href="index.html">Home</a>
    <a href="friends.html">Friends</a>
    <a href="blog.html">Blog</a>
  </nav>

  <!-- Stars Background -->
  <div class="stars">
    <div class="star"></div>
    <div class="star"></div>
    <div class="star"></div>
    <div class="star"></div>
    <div class="star"></div>
    <div class="star"></div>
    <div class="star"></div>
    <div class="star"></div>
    <div class="star"></div>
    <div class="star"></div>
  </div>

  <h1>Mengenal dan Menyunting _config.yml</h1>
  <p><em>20 Feb 2025</em></p>
  <p><strong>_config.yml</strong> adalah file konfigurasi utama dalam proyek Jekyll yang digunakan untuk mengatur berbagai aspek dari situs statis kita.</p>

  <h2>1. Apa itu _config.yml?</h2>
  <p>File ini berisi pengaturan global untuk situs Jekyll Anda, seperti nama situs, deskripsi, URL, dan lainnya. File ini ditulis dalam format YAML yang simpel dan mudah dibaca.</p>

  <h2>2. Contoh isi _config.yml</h2>
  <pre><code>title: Situs Saya
description: Situs blog pribadi menggunakan Jekyll
baseurl: "" # kosongkan jika di root
url: "https://namakamu.github.io"

theme: minima
plugins:
  - jekyll-feed

author:
  name: Yumna Assyifa
  email: email@example.com

markdown: kramdown
highlighter: rouge</code></pre>

  <h2>3. Pengaturan Umum</h2>
  <ul>
    <li><strong>title</strong>: Judul situs yang akan tampil di halaman browser.</li>
    <li><strong>description</strong>: Deskripsi singkat tentang situs Anda.</li>
    <li><strong>url</strong>: Alamat utama situs Anda di hosting.</li>
    <li><strong>baseurl</strong>: Jika disimpan di subfolder (seperti GitHub Pages), isi sesuai nama repo.</li>
    <li><strong>theme</strong>: Tema yang digunakan.</li>
    <li><strong>plugins</strong>: Plugin tambahan seperti `jekyll-feed`, `jekyll-seo-tag`, dll.</li>
  </ul>

  <h2>4. Tips Menyunting</h2>
  <ul>
    <li>Gunakan indentasi spasi, bukan tab.</li>
    <li>Setelah mengubah, restart server Jekyll agar perubahan terbaca.</li>
    <li>Periksa di terminal jika ada kesalahan YAML.</li>
  </ul>

  <h2>5. Menambahkan Navigasi Kustom</h2>
  <p>Contoh jika ingin menambahkan menu kustom di header:</p>
  <pre><code>nav:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
  - title: Tentang
    url: /about/</code></pre>

  <h2>6. Kesimpulan</h2>
  <p>_config.yml memberi kontrol penuh terhadap pengaturan proyek Jekyll Anda. Dengan memahami dan mengedit file ini, Anda bisa menyesuaikan tampilan, fungsi, dan struktur blog sesuai keinginan.</p>

</body>
</html>
